[custom.all.type-driven-dev-2023]
type = "local"
path = "."
ipkg = "type-driven-dev-2023.ipkg"
test = "test/test.ipkg"

[custom.all.type-driven-dev-2023-test]
type = "local"
path = "test"
ipkg = "test.ipkg"